# Setup
title:               Bootcamp for Data Chemistry
tagline:             '2025'
description:         '9/22 - 9/26, University of Notre Dame'
url:                 https://bootcampchem2025.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Haomin
  url:               https://zhmzm.github.io/
  email:             hzhuang2@nd.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
